### ISSUE TITLE
Add bibtex by URL with public link

### ISSUE THREAD

**Issue by nuest** [CitationGecko/gecko-react#25]
Instead of uploading a bibtex, it would be useful if a .bib file could be referenced by URL, ideally with a public link, like http://citationgecko.com?bib=https://github.io/mypaper/references.bib

This would allow to generate direkt links for online writing tools ("Open as seed in citation gecko"), or load a .bib file from GitHub directly.

**Comment by barney-walker** [comment]
This is now live! Thanks to @xRadne
