### ISSUE TITLE
Filter null values

### ISSUE THREAD

**Issue by catap** [CitationGecko/gecko-react#44]
Hey,

I've tried to use this tools and it has a lot of null value as recommended pages. Any way to filter it out?

<img width="407" alt="Screenshot 2020-01-29 10 29 36" src="https://user-images.githubusercontent.com/37775/73344275-5e177a00-4282-11ea-9e35-b1dcc3e2f360.png">

**Comment by barney-walker** [comment]
hmmm I can add a filter for 'has title'. I should also at least display the DOI if there is no other metadata rather than just null. Thanks for the feedback!

**Comment by barney-walker** [comment]
There was actually a load of unstructured information about those papers I wasn't displaying. I've updated it so all the info is displayed now even if unstructured.
