### ISSUE TITLE
Build Error: Webpack - Module not found

### ISSUE THREAD

**Issue by derikon** [CitationGecko/gecko-react#47]
I really like your online demo and tried to build the app locally. Unfortunately I ran into build errors thrown by webpack in **build.js** at `compiler.run(config);` when running `npm run build` from terminal. 

## Error Message

```
npm run build

> gecko-react@0.1.0 build ./Citation_Gecko/gecko-react
node scripts/build.js

Creating an optimized production build...
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .

Failed to compile.

Module not found: Error: Can't resolve 'data-modules' in './Citation_Gecko/gecko-react/src'
```

## Setup and Environment

+ macOS 10.15.4
+ Node 13.13.0
+ NPM 6.14.4
+ gecko-react commit [168bb40](https://github.com/CitationGecko/gecko-react/commit/168bb403164cd299013eb85284216d7e98021d22)

**Comment by barney-walker** [comment]
Yep I can reproduce this issue on mac but not windows. Probably an issue to do with how file paths are specified. Looking into it.

**Comment by barney-walker** [comment]
Okay, it should be working now can you confirm?

**Comment by xRadne** [comment]
I can confirm that this solved it for me. (Using windows)
