### ISSUE TITLE
Hover on nodes does not consistently show title

### ISSUE THREAD

**Issue by pesho-ivanov** [CitationGecko/gecko-react#7]
Sometimes showing the paper title does not work for hovering on recommended nodes or/and for hovering on seed nodes. I suspect the issue is outside CitationGecko (maybe D3).

Half of the times the problems can be reproduced by:
start the service -> choose "show me an example!" -> choose "Papers Citing Seed Papers" -> hover a seed and a recommended node

**Comment by bjw49** [comment]
This should be fixed now in the React version
