### ISSUE TITLE
Use the OpenCitations Indexes Unifying API

### ISSUE THREAD

**Issue by essepuntato** [CitationGecko/gecko-react#9]
Today, it has been released the Unifying API for all the OpenCitations Indexes (https://w3id.org/oc/index/api/v1), that can be used for getting citation information from any OpenCitations Index (COCI and CROCI so far). The integration with this API will guarantee to access to new indexes without further modification.

**Comment by bjw49** [comment]
Thanks for this. I have updated to use the new unifying API for /citations.

Out of interest how does the data served by /metadata and /references endpoint compare to that from the CrossRef API? Is one more complete / up-to-date than the other, will they give me the same data, or are they partially overlapping?

**Comment by essepuntato** [comment]
HI @barney-walker 

All the information about the citations (i.e. A cites B) in any API operation are actually obtained from the indexes – and may, e.g. in COCI, being derived from specific dumps of existing data such as Crossref. Thus, one has to wait for a new update of the Indexes for getting updated data with the source – more later this month... :-)

However, currently the metadata of the article obtained by executing the "/metadata" operation are actually derived from a live call to external services, including Crossref.
